[config]
type = "pipeline"
chartbook_format_version = "0.0.2"

[site]
title = "Monetary Tightening and US Bank Fragility"
author = "Summer Han, Joe Wang"
copyright = "2025"
logo_path = ""
favicon_path = ""

[pipeline]
id = "P0"
pipeline_name = "Monetary Tightening and US Bank Fragility"
pipeline_description = "Replicates Table 1, Table A1, and Figure A1 from Jiang et al. (2024) using data from WRDS, then updates the analysis through 2025 by scraping real-time data from FFIEC to monitor current mark-to-market losses and uninsured deposit exposure in US banks."
lead_pipeline_developer = "Summer Han, Joe Wang"
contributors = ["Summer Han, Joe Wang"]
software_modules_command = "module load anaconda3/3.11.4 TeXLive/2023"
runs_on_grid_or_windows_or_other = "Windows/Linux/MacOS"
git_repo_URL = ""
README_file_path = "./README.md"



[dataframes]


[dataframes.RCFD_Series_1]
dataframe_name = "FFEIC Call Report Data"
short_description_df = "Call Report Data from FFEIC on WRDS from 2021-12-31 to 2023-12-31"
data_sources = ["WRDS", "FFIEC"]
data_providers = ["WRDS", "FFIEC"]
topic_tags = ["Banks", "Call Reports"]
how_is_pulled = "WRDS Web API via Python"
path_to_parquet_data = "./_data/RCFD_Series_1.parquet"
date_col = "rssd9999"
dataframe_docs_path = "./docs_src/dataframes/RCFD_Series_1.md"


[charts]


[charts.total_cash]
chart_name = "Total Cash by Banks"
short_description_chart = "Total Cash by Banks from 2021-12-31 to 2023-12-31"
dataframe_id = "RCFD_Series_1"
topic_tags = ["Banks", "Call Reports"]
data_series_start_date = "1/31/2012"
units = "dollars"
path_to_html_chart = "./_output/example_plot.html"
chart_docs_path = "./docs_src/charts/total_cash.md"

